save_dir: ./logs
name: ${hydra:runtime.choices.model}_vs${model.vocab_size}_dm${model.d_model}_nh${model.n_head}_${hydra:runtime.choices.dataset}_ts${train.time_steps}_lr${train.learning_rate}
version: ${now:%Y-%m-%d-%H-%M-%S}
